### ISSUE TITLE
Problems with Rust execution

### ISSUE THREAD

**Issue by LeonBirkel** [HuakunShen/tauri-plugin-system-info#7]
Hey,

I am really exited for your plugin and are looking forward to use it, if I use it in TS, everything works fine. However, I need to get the same information your example provides for TS in Rust.  When I try to follow your explanation about how to do so I encoutner following error. 

I am new to Tauri and Rust, so it's probably my fault, I still would appreciate help a lot :D

`use tauri_plugin_system_info::utils::{SysInfo, SysInfoState};`

```
error[E0603]: module `utils` is private
  --> src\lib.rs:10:31
   |
10 | use tauri_plugin_system_info::utils::{SysInfo, SysInfoState};
   |                               ^^^^^ private module
   |
note: the module `utils` is defined here
  --> C:\Users\leonb\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-system-info-2.0.7\src/lib.rs:15:1
   |
15 | mod utils;
   | ^^^^^^^^^
```

**Comment by HuakunShen** [comment]
I could replicate this, thanks for pointing this out. I guess it was my mistake when migrating from V1 plugin.
I will fix it.

**Comment by HuakunShen** [comment]
Fixed in v2.0.8.
See https://docs.rs/tauri-plugin-system-info/2.0.8/tauri_plugin_system_info/ for the exposed rust code.

**Comment by LeonBirkel** [comment]
Thank you very much for the quick response and the fix. I really appreciate it!
